"""Write docs/CALIBRATION.md from the real grader and the synthetic demo data.

    python tools/calibration_report.py

The behaviour table is deterministic. The grade-versus-expert table is computed on the SYNTHETIC seed in a
throwaway folder, so it shows the method, never the grade's accuracy. Re-run `confusion()` (the Standards
page does, live) on real expert decisions to calibrate for real.
"""

import os
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
os.environ["STREAMPROOF_DATA"] = tempfile.mkdtemp(prefix="streamproof-calibration-")
os.environ.setdefault("STREAMPROOF_NETWORK", "0")
sys.path.insert(0, str(ROOT))

from app import calibration, config, seed  # noqa: E402


def main() -> None:
    store = seed.run()
    rep = calibration.report(store.all())
    c = rep["confusion"]
    lines = [
        "# Calibration report",
        "",
        "*Generated by `python tools/calibration_report.py`. Do not edit by hand.*",
        "",
        "The grade is rule-based: seven checks, 100 points, bands "
        + ", ".join(f"{b['grade']} from {b['from']}" for b in rep["bands"][:-1]) + ", D below 50 "
        "(`app/grading.py`). This report asks two questions and is honest about what each can and cannot show.",
        "",
        "> The grade says how well a report is **supported**. It is not the ecological status of the stream: "
        "formal assessment stays with the OneAquaHealth field protocols.",
        "",
        "## 1. What the rules do (a specification check)",
        "",
        "Reports built to isolate one weakness, graded by the real grader. This shows the rules behave as designed. "
        "It is **not** evidence that the grade predicts anything.",
        "",
        "| Scenario | What it isolates | Score | Grade |",
        "|---|---|---:|:-:|",
    ]
    for s in rep["scenarios"]:
        lines.append(f"| {s['name']} | {s['isolates']} | {s['score']} | {s['grade']} |")
    sc = {s["name"]: s for s in rep["scenarios"]}
    first = sc["First report: clear photo, good GPS, on the stream"]
    contra = sc["A nearby all-clear within 48 h contradicts it"]
    poor = sc["Observer mostly not confirmed (1 of 5 earlier reports)"]
    lines += [
        "",
        "**What this tells us, including the weaknesses**",
        "",
        f"- A lone newcomer tops out at **B** ({first['score']}/100): grade A needs a second person nearby or a "
        "proven track record. That is intended.",
        f"- A single agreeing neighbour lifts a lone report from B to A. This is generous: agreement is cheap to "
        "fake. The *trust level* (not the grade) is what resists it, because it counts different people spread in "
        "time or place, caps corroborations per account per day, and needs an expert for decision grade.",
        f"- A contradicting all-clear costs a report only {first['score'] - contra['score']} points "
        f"(still {contra['grade']}). The expert, not the grade, settles contradictions.",
        f"- An observer whose earlier reports were mostly not confirmed still gets {poor['grade']} "
        f"({poor['score']}/100): track record is worth at most 10 points.",
        "- A report with no photo cannot pass 60 points, so it can never be better than C.",
        "",
        "These are the first things to revisit once real decisions exist.",
        "",
        "## 2. Does the grade predict what experts decide?",
        "",
        "This is the calibration that matters: of the reports an expert decided, how often were grade A, B, C, D "
        "confirmed? Below is the **synthetic demo data**, so it only shows that the method works.",
        "",
        "| Grade | Decided | Confirmed | Not confirmed | Share confirmed |",
        "|:-:|---:|---:|---:|---:|",
    ]
    for r in c["rows"]:
        share = "n/a" if r["share_confirmed"] is None else f"{round(r['share_confirmed'] * 100)}%"
        lines.append(f"| {r['grade']} | {r['decided']} | {r['confirmed']} | {r['not_confirmed']} | {share} |")
    lines += [
        "",
        c["note"] or f"{c['decided']} decided reports: enough to quote rates.",
        "",
        "The Standards page in the web app shows the same table, computed live on whatever decisions exist "
        f"(rates appear once {c['min_decided']} reports are decided).",
        "",
        "## 3. Limits we know about",
        "",
    ]
    lines += [f"- {x}" for x in rep["limits"]]
    lines += [
        "- No real field photos or expert-labelled field data were available for this submission, so nothing here "
        "is a measured accuracy.",
        "",
        "## 4. How to calibrate for real",
        "",
        "1. Run a pilot where OneAquaHealth ecologists decide a sample of reports of every grade, not only the "
        "health-relevant ones, so the sample is not biased towards one end.",
        "2. Read the table above on those decisions; adjust the weights and bands in `app/grading.py` and the "
        "thresholds in `app/config.py`; repeat.",
        "3. Publish the table with its sample size, as here.",
        "",
        f"*Window and thresholds in force: nearby reports within {config.NEARBY_RADIUS_M} m and "
        f"{config.NEARBY_WINDOW_DAYS} days; advisory threshold "
        f"{config.ADVISORY_MIN_EXPERT} expert-verified or {config.ADVISORY_MIN_COMMUNITY} community-supported "
        "reports of the same sign. Illustrative defaults.*",
        "",
    ]
    out = ROOT / "docs" / "CALIBRATION.md"
    out.write_text("\n".join(lines), encoding="utf-8")
    print("wrote", out)


if __name__ == "__main__":
    main()
